// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type capper_type = 'nexus' | 'shiva' | 'cerberus' | 'ifrit' | 'deeppick'

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          username: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
          preferences: Json
          subscription_tier: 'free' | 'premium' | 'pro'
          units_per_bet: number
          total_units_bet: number
          total_units_won: number
          total_units_lost: number
          win_rate: number
          roi: number
        }
        Insert: {
          id: string
          email: string
          username?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
          preferences?: Json
          subscription_tier?: 'free' | 'premium' | 'pro'
          units_per_bet?: number
          total_units_bet?: number
          total_units_won?: number
          total_units_lost?: number
          win_rate?: number
          roi?: number
        }
        Update: {
          id?: string
          email?: string
          username?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
          preferences?: Json
          subscription_tier?: 'free' | 'premium' | 'pro'
          units_per_bet?: number
          total_units_bet?: number
          total_units_won?: number
          total_units_lost?: number
          win_rate?: number
          roi?: number
        }
      }
      games: {
        Row: {
          id: string
          sport: string
          league: string
          home_team: Json
          away_team: Json
          game_date: string
          game_time: string
          status: string
          venue: string
          weather: Json | null
          odds: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sport: string
          league: string
          home_team: Json
          away_team: Json
          game_date: string
          game_time: string
          status?: string
          venue: string
          weather?: Json | null
          odds: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sport?: string
          league?: string
          home_team?: Json
          away_team?: Json
          game_date?: string
          game_time?: string
          status?: string
          venue?: string
          weather?: Json | null
          odds?: Json
          created_at?: string
          updated_at?: string
        }
      }
      picks: {
        Row: {
          id: string
          user_id: string
          game_id: string
          sport: string
          bet_type: string
          selection: string
          odds: number
          confidence: string
          units: number
          potential_payout: number
          status: string
          reasoning: string
          data_points: Json
          created_at: string
          updated_at: string
          graded_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          game_id: string
          sport: string
          bet_type: string
          selection: string
          odds: number
          confidence: string
          units: number
          potential_payout: number
          status?: string
          reasoning: string
          data_points?: Json
          created_at?: string
          updated_at?: string
          graded_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          game_id?: string
          sport?: string
          bet_type?: string
          selection?: string
          odds?: number
          confidence?: string
          units?: number
          potential_payout?: number
          status?: string
          reasoning?: string
          data_points?: Json
          created_at?: string
          updated_at?: string
          graded_at?: string | null
        }
      }
      pick_results: {
        Row: {
          id: string
          pick_id: string
          outcome: string
          actual_result: string
          units_won: number
          units_lost: number
          net_units: number
          graded_at: string
          notes: string | null
        }
        Insert: {
          id?: string
          pick_id: string
          outcome: string
          actual_result: string
          units_won: number
          units_lost: number
          net_units: number
          graded_at?: string
          notes?: string | null
        }
        Update: {
          id?: string
          pick_id?: string
          outcome?: string
          actual_result?: string
          units_won?: number
          units_lost?: number
          net_units?: number
          graded_at?: string
          notes?: string | null
        }
      }
      performance_metrics: {
        Row: {
          id: string
          user_id: string
          period: string
          total_picks: number
          wins: number
          losses: number
          pushes: number
          win_rate: number
          units_bet: number
          units_won: number
          units_lost: number
          net_units: number
          roi: number
          longest_win_streak: number
          longest_loss_streak: number
          current_streak: number
          current_streak_type: string
          average_odds: number
          best_performing_sport: string
          best_performing_bet_type: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          period: string
          total_picks?: number
          wins?: number
          losses?: number
          pushes?: number
          win_rate?: number
          units_bet?: number
          units_won?: number
          units_lost?: number
          net_units?: number
          roi?: number
          longest_win_streak?: number
          longest_loss_streak?: number
          current_streak?: number
          current_streak_type?: string
          average_odds?: number
          best_performing_sport?: string
          best_performing_bet_type?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          period?: string
          total_picks?: number
          wins?: number
          losses?: number
          pushes?: number
          win_rate?: number
          units_bet?: number
          units_won?: number
          units_lost?: number
          net_units?: number
          roi?: number
          longest_win_streak?: number
          longest_loss_streak?: number
          current_streak?: number
          current_streak_type?: string
          average_odds?: number
          best_performing_sport?: string
          best_performing_bet_type?: string
          created_at?: string
          updated_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          message: string
          read: boolean
          created_at: string
          action_url: string | null
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          message: string
          read?: boolean
          created_at?: string
          action_url?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          message?: string
          read?: boolean
          created_at?: string
          action_url?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
