import { SpecNode, SpecTreeData } from './types'

/**
 * Betting-focused skill tree for DeepPick cappers
 * MOBILITY = Market speed & quick execution
 * CONDITIONING = Consistency & reliability
 * SURVIVAL = Risk management & bankroll protection
 */
export const createInitialSpecTree = (): SpecTreeData => {
  const nodes: SpecNode[] = [
    // ========== MOBILITY BRANCH (Yellow) ==========
    // Market speed, quick analysis, rapid execution
    {
      id: 'mobility-0',
      name: 'MOBILITY',
      icon: '⚡',
      branch: 'mobility',
      tier: 0,
      maxLevel: 5,
      currentLevel: 1,
      locked: false,
      prerequisites: [],
      x: 50,
      y: 85,
      connections: ['mobility-1', 'mobility-2', 'mobility-3', 'mobility-4'],
    },
    // Tier 1: Basic speed skills
    {
      id: 'mobility-1',
      name: 'Quick Scan',
      icon: '👁️',
      branch: 'mobility',
      tier: 1,
      maxLevel: 5,
      currentLevel: 0,
      locked: false,
      prerequisites: ['mobility-0'],
      x: 35,
      y: 70,
      connections: ['mobility-5'],
    },
    {
      id: 'mobility-2',
      name: 'Rapid Entry',
      icon: '🚀',
      branch: 'mobility',
      tier: 1,
      maxLevel: 5,
      currentLevel: 0,
      locked: false,
      prerequisites: ['mobility-0'],
      x: 65,
      y: 70,
      connections: ['mobility-6'],
    },
    // Tier 2: Advanced speed (locked)
    {
      id: 'mobility-3',
      name: 'Line Movement',
      icon: '📈',
      branch: 'mobility',
      tier: 2,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-0'],
      x: 25,
      y: 55,
      connections: ['mobility-5'],
    },
    {
      id: 'mobility-4',
      name: 'Instant Value',
      icon: '💎',
      branch: 'mobility',
      tier: 2,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-0'],
      x: 75,
      y: 55,
      connections: ['mobility-6'],
    },
    // Tier 3: Split paths
    {
      id: 'mobility-5',
      name: 'Sharp Money',
      icon: '🎯',
      branch: 'mobility',
      tier: 3,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-1', 'mobility-3'],
      x: 30,
      y: 40,
      connections: ['mobility-7', 'mobility-8'],
    },
    {
      id: 'mobility-6',
      name: 'Live Betting',
      icon: '🔥',
      branch: 'mobility',
      tier: 3,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-2', 'mobility-4'],
      x: 70,
      y: 40,
      connections: ['mobility-9', 'mobility-10'],
    },
    // Tier 4: Specialization paths
    {
      id: 'mobility-7',
      name: 'Pattern Recognition',
      icon: '🔍',
      branch: 'mobility',
      tier: 4,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-5'],
      x: 20,
      y: 25,
      connections: ['mobility-11'],
    },
    {
      id: 'mobility-8',
      name: 'Reverse Line',
      icon: '↻',
      branch: 'mobility',
      tier: 4,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-5'],
      x: 40,
      y: 25,
      connections: ['mobility-11'],
    },
    {
      id: 'mobility-9',
      name: 'In-Game Edge',
      icon: '⚡',
      branch: 'mobility',
      tier: 4,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-6'],
      x: 60,
      y: 25,
      connections: ['mobility-12'],
    },
    {
      id: 'mobility-10',
      name: 'Momentum Shift',
      icon: '🌊',
      branch: 'mobility',
      tier: 4,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-6'],
      x: 80,
      y: 25,
      connections: ['mobility-12'],
    },
    // Tier 5: Ultimate skills
    {
      id: 'mobility-11',
      name: 'Nexus Mastery',
      icon: '🌟',
      branch: 'mobility',
      tier: 5,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-7', 'mobility-8'],
      x: 30,
      y: 10,
      connections: ['mobility-13'],
    },
    {
      id: 'mobility-12',
      name: 'Live Mastery',
      icon: '⚡',
      branch: 'mobility',
      tier: 5,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-9', 'mobility-10'],
      x: 70,
      y: 10,
      connections: ['mobility-14'],
    },
    {
      id: 'mobility-13',
      name: 'Market Dominance',
      icon: '👑',
      branch: 'mobility',
      tier: 6,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-11'],
      x: 30,
      y: -5,
      connections: [],
    },
    {
      id: 'mobility-14',
      name: 'Perfect Timing',
      icon: '⏱️',
      branch: 'mobility',
      tier: 6,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['mobility-12'],
      x: 70,
      y: -5,
      connections: [],
    },

    // ========== CONDITIONING BRANCH (Green) ==========
    // Consistency, reliability, endurance
    {
      id: 'conditioning-0',
      name: 'CONDITIONING',
      icon: '💪',
      branch: 'conditioning',
      tier: 0,
      maxLevel: 5,
      currentLevel: 1,
      locked: false,
      prerequisites: [],
      x: 15,
      y: 85,
      connections: ['conditioning-1'],
    },
    {
      id: 'conditioning-1',
      name: 'Steady Hand',
      icon: '✋',
      branch: 'conditioning',
      tier: 1,
      maxLevel: 5,
      currentLevel: 1,
      locked: false,
      prerequisites: ['conditioning-0'],
      x: 15,
      y: 70,
      connections: ['conditioning-2', 'conditioning-3'],
    },
    {
      id: 'conditioning-2',
      name: 'Statistical Edge',
      icon: '📊',
      branch: 'conditioning',
      tier: 2,
      maxLevel: 5,
      currentLevel: 0,
      locked: false,
      prerequisites: ['conditioning-1'],
      x: 5,
      y: 55,
      connections: ['conditioning-4'],
    },
    {
      id: 'conditioning-3',
      name: 'Elo Mastery',
      icon: '🎲',
      branch: 'conditioning',
      tier: 2,
      maxLevel: 5,
      currentLevel: 0,
      locked: false,
      prerequisites: ['conditioning-1'],
      x: 25,
      y: 55,
      connections: [],
    },
    {
      id: 'conditioning-4',
      name: 'Regression Expert',
      icon: '📉',
      branch: 'conditioning',
      tier: 3,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['conditioning-2'],
      x: 5,
      y: 40,
      connections: ['conditioning-5'],
    },
    {
      id: 'conditioning-5',
      name: 'Shiva Core',
      icon: '🧘',
      branch: 'conditioning',
      tier: 4,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['conditioning-4'],
      x: 5,
      y: 25,
      connections: ['conditioning-6'],
    },
    {
      id: 'conditioning-6',
      name: 'Statistical God',
      icon: '🔬',
      branch: 'conditioning',
      tier: 5,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['conditioning-5'],
      x: 5,
      y: 10,
      connections: [],
    },

    // ========== SURVIVAL BRANCH (Red) ==========
    // Risk management, bankroll protection, loss avoidance
    {
      id: 'survival-0',
      name: 'SURVIVAL',
      icon: '🛡️',
      branch: 'survival',
      tier: 0,
      maxLevel: 5,
      currentLevel: 0,
      locked: false,
      prerequisites: [],
      x: 85,
      y: 85,
      connections: ['survival-1'],
    },
    {
      id: 'survival-1',
      name: 'Bankroll Guard',
      icon: '💰',
      branch: 'survival',
      tier: 1,
      maxLevel: 5,
      currentLevel: 0,
      locked: false,
      prerequisites: ['survival-0'],
      x: 85,
      y: 70,
      connections: ['survival-2', 'survival-3'],
    },
    {
      id: 'survival-2',
      name: 'Kelly Criterion',
      icon: '📐',
      branch: 'survival',
      tier: 2,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['survival-1'],
      x: 75,
      y: 55,
      connections: ['survival-4'],
    },
    {
      id: 'survival-3',
      name: 'Stop Loss',
      icon: '⛔',
      branch: 'survival',
      tier: 2,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['survival-1'],
      x: 95,
      y: 55,
      connections: ['survival-5'],
    },
    {
      id: 'survival-4',
      name: 'Unit Sizing',
      icon: '⚖️',
      branch: 'survival',
      tier: 3,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['survival-2'],
      x: 75,
      y: 40,
      connections: ['survival-6'],
    },
    {
      id: 'survival-5',
      name: 'Risk Reversal',
      icon: '🔄',
      branch: 'survival',
      tier: 3,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['survival-3'],
      x: 95,
      y: 40,
      connections: [],
    },
    {
      id: 'survival-6',
      name: 'Bankroll Master',
      icon: '🏦',
      branch: 'survival',
      tier: 4,
      maxLevel: 5,
      currentLevel: 0,
      locked: true,
      prerequisites: ['survival-4'],
      x: 75,
      y: 25,
      connections: [],
    },
  ]

  // Organize nodes by branch
  const mobilityNodes = nodes.filter((n) => n.branch === 'mobility')
  const conditioningNodes = nodes.filter((n) => n.branch === 'conditioning')
  const survivalNodes = nodes.filter((n) => n.branch === 'survival')

  return {
    branches: {
      mobility: mobilityNodes,
      conditioning: conditioningNodes,
      survival: survivalNodes,
    },
    branchLevels: {
      mobility: 1,
      conditioning: 1,
      survival: 0,
    },
  }
}
