-- AI Capper Enhancement System
-- Supports 2-run hybrid approach: Perplexity + ChatGPT with StatMuse

-- Create ai_research_runs table
CREATE TABLE IF NOT EXISTS ai_research_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  game_id UUID NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  capper TEXT NOT NULL,
  
  -- Run info
  run_number INTEGER NOT NULL CHECK (run_number IN (1, 2)),
  run_type TEXT NOT NULL CHECK (run_type IN ('perplexity_statmuse', 'chatgpt_statmuse')),
  ai_provider TEXT NOT NULL CHECK (ai_provider IN ('perplexity', 'chatgpt')),
  
  -- StatMuse questions (2 per run)
  statmuse_questions JSONB NOT NULL DEFAULT '[]',
  statmuse_answers JSONB NOT NULL DEFAULT '[]',
  
  -- AI analysis results
  ai_analysis JSONB NOT NULL DEFAULT '{}',
  
  -- Cost tracking
  cost DECIMAL(6,4) NOT NULL DEFAULT 0,
  
  -- Metadata
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  duration_seconds INTEGER,
  
  UNIQUE(game_id, capper, run_number)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_ai_runs_game ON ai_research_runs(game_id);
CREATE INDEX IF NOT EXISTS idx_ai_runs_capper ON ai_research_runs(capper);
CREATE INDEX IF NOT EXISTS idx_ai_runs_timestamp ON ai_research_runs(timestamp DESC);

-- Create capper_settings table
CREATE TABLE IF NOT EXISTS capper_settings (
  capper TEXT PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT false,
  
  -- Timing
  hours_before_game INTEGER NOT NULL DEFAULT 4,
  
  -- Cost control
  max_games_per_day INTEGER NOT NULL DEFAULT 30,
  daily_budget DECIMAL(8,2) NOT NULL DEFAULT 40.00,
  cost_per_game DECIMAL(6,4) NOT NULL DEFAULT 0.035,
  
  -- Weed-out filters
  weedout_filters JSONB NOT NULL DEFAULT '{
    "min_spread": 0,
    "max_spread": 12,
    "min_line_movement": 0.5,
    "min_hours_until_game": 4
  }',
  
  -- AI configuration
  run1_focus JSONB NOT NULL DEFAULT '[]',
  run2_focus JSONB NOT NULL DEFAULT '[]',
  
  -- Thresholds
  min_confidence DECIMAL(3,1) NOT NULL DEFAULT 7.0,
  
  -- Personality
  betting_style TEXT,
  specialties JSONB NOT NULL DEFAULT '[]',
  risk_tolerance TEXT DEFAULT 'medium',
  
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert default settings for Shiva
INSERT INTO capper_settings (
  capper, 
  enabled, 
  hours_before_game,
  run1_focus,
  run2_focus,
  betting_style,
  specialties
) VALUES (
  'shiva',
  true,
  4,
  '["Recent form and momentum", "Head-to-head history", "Scoring trends and matchup efficiency", "Situational factors (rest, schedule)"]'::jsonb,
  '["Latest injuries and lineup changes", "Weather conditions", "Betting market trends", "Score prediction and validation"]'::jsonb,
  'Multi-model destroyer - seeks consensus across multiple analytical lenses',
  '["matchup_efficiency", "situational_analysis", "consensus_building"]'::jsonb
) ON CONFLICT (capper) DO NOTHING;

-- Add AI enhancement columns to picks table
ALTER TABLE picks 
  ADD COLUMN IF NOT EXISTS ai_research_id UUID REFERENCES ai_research_runs(id),
  ADD COLUMN IF NOT EXISTS ai_factors JSONB,
  ADD COLUMN IF NOT EXISTS ai_writeup TEXT,
  ADD COLUMN IF NOT EXISTS ai_bold_prediction TEXT,
  ADD COLUMN IF NOT EXISTS total_ai_cost DECIMAL(6,4) DEFAULT 0;

-- Create view for AI-enhanced picks
CREATE OR REPLACE VIEW ai_enhanced_picks AS
SELECT 
  p.id,
  p.game_id,
  p.capper,
  p.pick_type,
  p.selection,
  p.odds,
  p.units,
  p.confidence,
  p.status,
  p.ai_writeup,
  p.ai_bold_prediction,
  p.total_ai_cost,
  p.created_at,
  g.home_team,
  g.away_team,
  g.game_date,
  g.sport,
  -- Aggregate AI research runs
  (
    SELECT json_agg(
      json_build_object(
        'run_number', run_number,
        'ai_provider', ai_provider,
        'statmuse_questions', statmuse_questions,
        'cost', cost
      ) ORDER BY run_number
    )
    FROM ai_research_runs
    WHERE game_id = p.game_id AND capper = p.capper
  ) as ai_runs
FROM picks p
JOIN games g ON p.game_id = g.id
WHERE p.total_ai_cost > 0;

COMMENT ON TABLE ai_research_runs IS 'Tracks AI research runs (Perplexity + ChatGPT with StatMuse)';
COMMENT ON TABLE capper_settings IS 'Configuration for each AI-enhanced capper';
COMMENT ON VIEW ai_enhanced_picks IS 'All picks generated with AI enhancement';

COMMENT ON COLUMN ai_research_runs.statmuse_questions IS '2 clever questions generated by AI for StatMuse';
COMMENT ON COLUMN ai_research_runs.statmuse_answers IS 'Answers scraped from StatMuse (free)';
COMMENT ON COLUMN ai_research_runs.cost IS 'Cost of this AI run (Perplexity: $0.025, ChatGPT: $0.01)';

COMMENT ON COLUMN picks.ai_writeup IS 'Comprehensive AI-generated analysis and reasoning';
COMMENT ON COLUMN picks.ai_bold_prediction IS 'AI bold prediction (player performance, key moment, etc.)';
COMMENT ON COLUMN picks.total_ai_cost IS 'Total cost of AI research for this pick (~$0.035)';

